apiVersion: v1
kind: Service
metadata:
  name: propagator-webhook-service
  namespace: open-cluster-management
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    webhook-origin: governance-policy-propagator
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: propagator-webhook-serving-cert
  namespace: open-cluster-management
spec:
  dnsNames:
  - propagator-webhook-service.open-cluster-management.svc
  - propagator-webhook-service.open-cluster-management.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: propagator-webhook-selfsigned-issuer
  secretName: propagator-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: propagator-webhook-selfsigned-issuer
  namespace: open-cluster-management
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: open-cluster-management/propagator-webhook-serving-cert
  name: propagator-webhook-validating-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: propagator-webhook-service
      namespace: open-cluster-management
      path: /validate-policy-open-cluster-management-io-v1-policy
  failurePolicy: Ignore
  name: policy.open-cluster-management.io.webhook
  rules:
  - apiGroups:
    - policy.open-cluster-management.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - policies
  sideEffects: None
