name: Upstream reference checks
on:
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+
defaults:
  run:
    shell: bash
jobs:
  upstream-refs:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    name: Upstream reference checks
    steps:
      - name: Checkout propagator
        uses: actions/checkout@v7
        with:
          path: governance-policy-propagator
      - name: Checkout Policy Framework
        uses: actions/checkout@v7
        with:
          path: governance-policy-framework
          repository: stolostron/governance-policy-framework
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: governance-policy-framework/go.mod
          cache-dependency-path: governance-policy-framework/go.sum
      - name: Detect upstream references that should be replaced
        working-directory: governance-policy-propagator
        run: |
          ./../governance-policy-framework/build/detect-upstream.sh -m "cat Makefile" -i "go list -mod readonly -m all" -q "deploy/manager/manager.yaml" -q "deploy/operator.yaml"
